
[package]
edition = "2021"
name = "pb-mathcat-node-wrapper"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
mathcat = "^0.7.2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
