/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getMathcatVersion(): string

export declare function getSpeechTextFromMathcat(input: string): string

export declare function initMathcat(rulesPath?: string | undefined | null): string

export declare function setMathcatPreference(key: string, value: string): string
